import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";

import { palette } from "@/components/hub-ui";

type Action = { label: string; detail: string; icon: keyof typeof MaterialIcons.glyphMap; tone?: "normal" | "danger"; onPress: () => void };
export function ChatActionsSheet({ visible, onClose, onHistory, onArchive, onExport, onSettings, onClear }: { visible: boolean; onClose: () => void; onHistory: () => void; onArchive: () => void; onExport: () => void; onSettings: () => void; onClear: () => void }) {
  const actions: Action[] = [{ label: "Thread History", detail: "Xem lịch sử của cuộc hội thoại hiện tại", icon: "history", onPress: onHistory }, { label: "Archive Chat", detail: "Lưu cuộc hội thoại để mở lại sau", icon: "inventory-2", onPress: onArchive }, { label: "Export Chat", detail: "Sao chép nội dung hội thoại ra clipboard", icon: "ios-share", onPress: onExport }, { label: "Conversation Settings", detail: "Name, Instruction và model settings", icon: "tune", onPress: onSettings }, { label: "Clear All Messages", detail: "Xoá toàn bộ tin nhắn trong cuộc hội thoại này", icon: "delete-outline", tone: "danger", onPress: onClear }];
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.root}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.header}><Pressable onPress={onClose} style={styles.back}><MaterialIcons name="arrow-back-ios-new" size={18} color="#FFFFFF" /></Pressable><Text style={styles.title}>Conversation</Text><View style={styles.spacer} pointerEvents="none" /></View>{actions.map((action, index) => <Pressable key={action.label} onPress={() => { action.onPress(); onClose(); }} style={({ pressed }) => [styles.row, index > 0 && styles.divider, { opacity: pressed ? 0.7 : 1 }]}><View style={[styles.icon, action.tone === "danger" && styles.dangerIcon]}><MaterialIcons name={action.icon} size={19} color={action.tone === "danger" ? palette.error : palette.navy} /></View><View style={styles.copy}><Text style={[styles.label, action.tone === "danger" && styles.dangerText]}>{action.label}</Text><Text style={styles.detail}>{action.detail}</Text></View><MaterialIcons name="chevron-right" size={20} color="#969696" /></Pressable>)}</View></View></Modal>;
}
const styles = StyleSheet.create({ root: { flex: 1, justifyContent: "flex-end" }, scrim: { flex: 1, backgroundColor: "rgba(0,0,0,.68)" }, sheet: { backgroundColor: "#1E1E1E", borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderColor: "#4E4E4E", paddingHorizontal: 16, paddingBottom: 20 }, header: { height: 52, alignItems: "center", justifyContent: "center", borderBottomWidth: 1, borderBottomColor: "#363636" }, back: { position: "absolute", left: 0, height: 38, width: 38, alignItems: "center", justifyContent: "center" }, spacer: { position: "absolute", right: 0, height: 38, width: 38 }, title: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, row: { minHeight: 65, flexDirection: "row", alignItems: "center", gap: 10 }, divider: { borderTopWidth: 1, borderTopColor: "#343434" }, icon: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#213C53" }, dangerIcon: { backgroundColor: "#3D2525" }, copy: { flex: 1, gap: 2 }, label: { color: "#EEEEEE", fontSize: 13, fontWeight: "800" }, dangerText: { color: "#FF8585" }, detail: { color: "#A5A5A5", fontSize: 10, lineHeight: 14 } });
