import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, palette } from "@/components/hub-ui";
import type { ChatMessage } from "@/lib/mcp-hub/chat";

export function ChatMessageItem({ message, reasoningOpen, onToggleReasoning, onCopy, onEdit, onRetry, onMore }: { message: ChatMessage; reasoningOpen: boolean; onToggleReasoning: () => void; onCopy: () => void; onEdit: () => void; onRetry: () => void; onMore: () => void }) {
  const assistant = message.role === "assistant";
  if (message.failure) return <View style={styles.wrap}><Card style={styles.failure}><View style={styles.failureHead}><MaterialIcons name="error-outline" size={18} color={palette.error} /><Text style={styles.failureTitle}>{message.failure.title}</Text></View><Text style={styles.failureMeta}>{message.failure.providerName} · {message.failure.modelId}</Text><Text style={styles.failureText}>{message.failure.detail}</Text><Text style={styles.failureAction}>{message.failure.action}</Text><Pressable onPress={onRetry} style={styles.retry}><MaterialIcons name="refresh" size={15} color="#FFFFFF" /><Text style={styles.retryText}>Retry</Text></Pressable></Card></View>;
  return <View style={[styles.wrap, message.role === "user" ? styles.userWrap : styles.assistantWrap]}><View style={[styles.bubble, message.role === "user" ? styles.userBubble : styles.assistantBubble]}><Text style={[styles.content, message.role === "user" && styles.userContent]}>{message.content}</Text></View>{message.attachments?.length ? <View style={styles.attachments}>{message.attachments.map((attachment) => attachment.type === "image" && attachment.uri ? <Image key={attachment.id} source={{ uri: attachment.uri }} style={styles.image} /> : <View key={attachment.id} style={styles.attachmentChip}><MaterialIcons name={attachment.type === "file" ? "attach-file" : "location-on"} size={14} color={palette.navy} /><Text style={styles.attachmentText} numberOfLines={1}>{attachment.label}</Text></View>)}</View> : null}{message.reasoning ? <View style={styles.reason}><Pressable onPress={onToggleReasoning} style={styles.reasonHead}><View style={styles.reasonTitleWrap}><MaterialIcons name="lightbulb-outline" size={17} color="#F5D25A" /><Text style={styles.reasonTitle}>Deeply thought</Text></View><MaterialIcons name={reasoningOpen ? "expand-less" : "expand-more"} size={20} color="#BEBEBE" /></Pressable>{reasoningOpen ? <Text style={styles.reasonText}>{message.reasoning}</Text> : null}</View> : null}{assistant ? <View style={styles.actions}><Pressable onPress={onCopy} style={styles.action}><MaterialIcons name="content-copy" size={16} color="#BDBDBD" /><Text style={styles.actionText}>Copy</Text></Pressable><Pressable onPress={onEdit} style={styles.action}><MaterialIcons name="edit" size={16} color="#BDBDBD" /><Text style={styles.actionText}>Edit</Text></Pressable><Pressable onPress={onRetry} style={styles.action}><MaterialIcons name="refresh" size={16} color="#BDBDBD" /><Text style={styles.actionText}>Retry</Text></Pressable><Pressable onPress={onMore} style={styles.action}><MaterialIcons name="more-horiz" size={18} color="#BDBDBD" /></Pressable></View> : null}{message.citations?.length ? <View style={styles.citations}><Text style={styles.citationLabel}>Nguồn web</Text>{message.citations.map((citation) => <Text key={citation.url} style={styles.citation} numberOfLines={1}>• {citation.title}</Text>)}</View> : null}</View>;
}

const styles = StyleSheet.create({ wrap: { gap: 7, maxWidth: "93%" }, userWrap: { alignSelf: "flex-end" }, assistantWrap: { alignSelf: "flex-start" }, bubble: { paddingHorizontal: 13, paddingVertical: 10, borderRadius: 16 }, userBubble: { backgroundColor: palette.navy, borderBottomRightRadius: 4 }, assistantBubble: { backgroundColor: "#383838", borderBottomLeftRadius: 4 }, content: { color: "#F2F2F2", fontSize: 14, lineHeight: 20 }, userContent: { color: "#FFFFFF" }, attachments: { gap: 6 }, image: { width: 170, height: 112, borderRadius: 10 }, attachmentChip: { flexDirection: "row", alignItems: "center", gap: 5, alignSelf: "flex-start", maxWidth: 235, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8, backgroundColor: "#283746" }, attachmentText: { color: "#BFE1FF", fontSize: 10, flexShrink: 1 }, reason: { backgroundColor: "#303030", borderRadius: 12, padding: 9, gap: 7 }, reasonHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, reasonTitleWrap: { flexDirection: "row", alignItems: "center", gap: 6 }, reasonTitle: { color: "#F5D25A", fontSize: 12, fontWeight: "800" }, reasonText: { color: "#C8C8C8", fontSize: 11, lineHeight: 17, borderLeftWidth: 2, borderLeftColor: "#F5D25A", paddingLeft: 8 }, actions: { flexDirection: "row", alignItems: "center", gap: 13, paddingLeft: 4 }, action: { flexDirection: "row", alignItems: "center", gap: 4, minHeight: 27 }, actionText: { color: "#BDBDBD", fontSize: 10 }, citations: { paddingLeft: 5, gap: 2 }, citationLabel: { color: palette.muted, fontSize: 9, fontWeight: "800" }, citation: { color: "#6DBBFF", fontSize: 10 }, failure: { backgroundColor: "#3C2525", borderColor: "#B94444", gap: 7 }, failureHead: { flexDirection: "row", alignItems: "center", gap: 7 }, failureTitle: { color: "#FF7676", fontSize: 13, fontWeight: "800" }, failureMeta: { color: "#BDBDBD", fontSize: 9, fontFamily: "monospace" }, failureText: { color: "#E2C0C0", fontSize: 11, lineHeight: 16 }, failureAction: { color: "#FF8A8A", fontSize: 11, lineHeight: 16, fontWeight: "700" }, retry: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#684040", paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8 }, retryText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" } });
