import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { palette } from "@/components/hub-ui";
import type { ChatTuning } from "@/lib/mcp-hub/chat-settings";

const TOKEN_OPTIONS = [512, 1024, 2048, 4096];
const TEMPERATURE_OPTIONS = [0, 0.3, 0.7, 1, 1.3];
const TOP_P_OPTIONS = [0.1, 0.5, 0.7, 0.9, 1];

export function ChatTuningSheet({ visible, tuning, conversationName, onChangeName, onChange, onClose }: { visible: boolean; tuning: ChatTuning; conversationName: string; onChangeName: (name: string) => void; onChange: (next: ChatTuning) => void; onClose: () => void }) {
  const numericRow = (label: string, value: string, icon: keyof typeof MaterialIcons.glyphMap = "info-outline") => <View style={styles.row}><Text style={styles.label}>{label}</Text><MaterialIcons name={icon} color="#A1A1A1" size={18} /><View style={styles.valuePill}><Text style={styles.valueText}>{value}</Text></View></View>;
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.root}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.sheetHeader}><Pressable testID="tuning-back" onPress={onClose} style={styles.back}><MaterialIcons name="arrow-back-ios-new" size={18} color="#FFFFFF" /></Pressable><Text style={styles.title}>Conversation Settings</Text><View style={styles.spacer} pointerEvents="none" /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={styles.section}>Conversation</Text><View style={styles.panel}><Text style={styles.fieldLabel}>Name</Text><TextInput value={conversationName} onChangeText={onChangeName} placeholder="Untitled" placeholderTextColor="#8E8E8E" style={styles.input} maxLength={80} /><Text style={styles.fieldLabel}>Instruction</Text><TextInput value={tuning.instruction} onChangeText={(instruction) => onChange({ ...tuning, instruction })} placeholder="You are a helpful assistant." placeholderTextColor="#8E8E8E" style={[styles.input, styles.textarea]} multiline maxLength={1000} /></View><Text style={styles.section}>Specific model settings</Text><View style={styles.panel}>{numericRow("Max Message Count in Context", "No Limit")}<View style={styles.slider}><View style={[styles.sliderFill, { width: "82%" }]} /><View style={styles.knob} /></View>{numericRow("Temperature", tuning.temperature.toFixed(1))}<View style={styles.choices}>{TEMPERATURE_OPTIONS.map((value) => <Pressable key={value} onPress={() => onChange({ ...tuning, temperature: value })} style={[styles.choice, tuning.temperature === value && styles.choiceActive]}><Text style={[styles.choiceText, tuning.temperature === value && styles.choiceTextActive]}>{value.toFixed(1)}</Text></Pressable>)}</View>{numericRow("Top P", tuning.topP.toFixed(1))}<View style={styles.choices}>{TOP_P_OPTIONS.map((value) => <Pressable key={value} onPress={() => onChange({ ...tuning, topP: value })} style={[styles.choice, tuning.topP === value && styles.choiceActive]}><Text style={[styles.choiceText, tuning.topP === value && styles.choiceTextActive]}>{value.toFixed(1)}</Text></Pressable>)}</View>{numericRow("Max Output Tokens", String(tuning.maxTokens))}<View style={styles.choices}>{TOKEN_OPTIONS.map((value) => <Pressable key={value} onPress={() => onChange({ ...tuning, maxTokens: value })} style={[styles.choice, tuning.maxTokens === value && styles.choiceActive]}><Text style={[styles.choiceText, tuning.maxTokens === value && styles.choiceTextActive]}>{value >= 1000 ? `${value / 1000}k` : value}</Text></Pressable>)}</View><View style={styles.switchRow}><Text style={styles.label}>Pause after every 25 steps</Text><View style={styles.switch}><View style={styles.switchKnob} /></View></View></View></ScrollView><Pressable onPress={onClose} style={styles.save}><Text style={styles.saveText}>Save</Text></Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({ root: { flex: 1, justifyContent: "flex-end" }, scrim: { flex: 1, backgroundColor: "rgba(0,0,0,.68)" }, sheet: { maxHeight: "91%", backgroundColor: "#1E1E1E", borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderColor: "#515151", paddingHorizontal: 17, paddingTop: 9, paddingBottom: 16 }, sheetHeader: { minHeight: 42, alignItems: "center", justifyContent: "center", marginBottom: 8 }, back: { position: "absolute", left: 0, width: 38, height: 38, alignItems: "center", justifyContent: "center" }, spacer: { position: "absolute", right: 0, width: 38, height: 38 }, title: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, content: { gap: 9, paddingBottom: 10 }, section: { color: "#F0F0F0", fontSize: 12, fontWeight: "800", marginTop: 4 }, panel: { borderWidth: 1, borderColor: "#474747", borderRadius: 14, padding: 12, gap: 10, backgroundColor: "#242424" }, fieldLabel: { color: "#CFCFCF", fontSize: 11, fontWeight: "700", marginBottom: -4 }, input: { minHeight: 40, borderWidth: 1, borderColor: "#4B4B4B", backgroundColor: "#303030", borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7, color: "#F4F4F4", fontSize: 12 }, textarea: { minHeight: 62, textAlignVertical: "top" }, row: { flexDirection: "row", alignItems: "center", gap: 7 }, label: { color: "#F0F0F0", fontSize: 12, fontWeight: "700", flex: 1 }, valuePill: { minWidth: 64, borderRadius: 14, paddingHorizontal: 8, paddingVertical: 6, backgroundColor: "#363636", borderWidth: 1, borderColor: "#515151", alignItems: "center" }, valueText: { color: "#C5C5C5", fontSize: 11, fontWeight: "700" }, slider: { height: 7, backgroundColor: "#4A4A4A", borderRadius: 8, position: "relative" }, sliderFill: { height: 7, backgroundColor: palette.navy, borderRadius: 8 }, knob: { position: "absolute", top: -5, left: "80%", width: 17, height: 17, borderRadius: 9, backgroundColor: "#F4F4F4", borderWidth: 3, borderColor: palette.navy }, choices: { flexDirection: "row", gap: 5, flexWrap: "wrap" }, choice: { minWidth: 39, paddingVertical: 6, paddingHorizontal: 8, backgroundColor: "#393939", borderRadius: 7, alignItems: "center" }, choiceActive: { backgroundColor: palette.navy }, choiceText: { color: "#C5C5C5", fontSize: 10, fontWeight: "800" }, choiceTextActive: { color: "#FFFFFF" }, switchRow: { flexDirection: "row", alignItems: "center", gap: 8 }, switch: { width: 43, height: 24, borderRadius: 14, backgroundColor: palette.navy, padding: 3, alignItems: "flex-end" }, switchKnob: { width: 18, height: 18, borderRadius: 9, backgroundColor: "#FFFFFF" }, save: { marginTop: 8, minHeight: 43, borderRadius: 22, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, saveText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" } });
