import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { Card, palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import type { McpToolDefinition } from "@/lib/mcp-hub/mcp-connection";

export function McpRunnerSheet({ visible, onClose, onLoad, onRun }: { visible: boolean; onClose: () => void; onLoad: () => Promise<McpToolDefinition[]>; onRun: (tool: McpToolDefinition, args: Record<string, unknown>) => Promise<void> }) {
  const [tools, setTools] = useState<McpToolDefinition[]>([]); const [selected, setSelected] = useState<McpToolDefinition | null>(null); const [argsText, setArgsText] = useState("{}"); const [loading, setLoading] = useState(false); const [running, setRunning] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!visible) return; setLoading(true); setError(null); void onLoad().then((next) => { setTools(next); setSelected(next[0] ?? null); setArgsText("{}"); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Không thể tải MCP tools.")).finally(() => setLoading(false)); }, [visible, onLoad]);
  const select = (tool: McpToolDefinition) => { setSelected(tool); setArgsText("{}"); setError(null); };
  const run = async () => { if (!selected) return; let args: Record<string, unknown>; try { const parsed: unknown = JSON.parse(argsText || "{}"); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("Tham số phải là một JSON object, ví dụ {}."); args = parsed as Record<string, unknown>; } catch (reason) { setError(reason instanceof Error ? reason.message : "JSON tham số không hợp lệ."); return; } setRunning(true); setError(null); try { await onRun(selected, args); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể gọi MCP tool."); } finally { setRunning(false); } };
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><View style={styles.header}><Pressable onPress={onClose} style={styles.back}><MaterialIcons name="arrow-back-ios-new" size={18} color={palette.text} /></Pressable><View><Text style={styles.title}>MCP Terminal</Text><Text style={styles.subtitle}>Chọn tool và gửi tham số JSON.</Text></View></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.note}>Lệnh được xử lý bởi MCP server đã kết nối, không phải Android shell. Chỉ chạy tool bạn chủ động chọn.</Text>{loading ? <View style={styles.loading}><ActivityIndicator color={palette.navy} /><Text style={styles.muted}>Đang gọi initialize → tools/list…</Text></View> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{!loading && !tools.length && !error ? <Text style={styles.muted}>Không có MCP Streamable HTTP đang bật/kết nối hoặc server không công bố tool.</Text> : null}{tools.map((tool) => <Pressable key={`${tool.serverId}:${tool.name}`} onPress={() => select(tool)} style={[styles.tool, selected?.serverId === tool.serverId && selected.name === tool.name && styles.toolActive]}><View style={styles.toolIcon}><MaterialIcons name="terminal" size={18} color={palette.navy} /></View><View style={styles.toolCopy}><Text style={styles.toolName}>{tool.serverName} · {tool.name}</Text><Text style={styles.toolDetail}>{tool.description}</Text></View><MaterialIcons name={selected?.serverId === tool.serverId && selected.name === tool.name ? "radio-button-checked" : "radio-button-unchecked"} size={19} color={palette.navy} /></Pressable>)}{selected ? <Card style={styles.argsCard}><Text style={styles.label}>Tham số cho {selected.name}</Text><Text style={styles.schema} numberOfLines={5}>{JSON.stringify(selected.inputSchema, null, 2)}</Text><TextInput value={argsText} onChangeText={setArgsText} multiline autoCapitalize="none" autoCorrect={false} editable={!running} placeholder="{}" placeholderTextColor="#8090A0" style={styles.input} /><Pressable onPress={() => void run()} disabled={running} style={({ pressed }) => [styles.run, { opacity: running ? 0.55 : pressed ? 0.8 : 1 }]}>{running ? <ActivityIndicator color="#FFFFFF" /> : <><MaterialIcons name="play-arrow" size={19} color="#FFFFFF" /><Text style={styles.runText}>Chạy tool</Text></>}</Pressable></Card> : null}</ScrollView></ScreenContainer></Modal>;
}

const styles = StyleSheet.create({ header: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 9, borderBottomWidth: 1, borderBottomColor: palette.border }, back: { width: 40, height: 40, alignItems: "center", justifyContent: "center", marginLeft: -5 }, title: { color: palette.text, fontSize: 15, fontWeight: "800" }, subtitle: { color: palette.muted, fontSize: 10, marginTop: 2 }, content: { paddingVertical: 15, gap: 10 }, note: { color: palette.muted, fontSize: 11, lineHeight: 16, padding: 10, borderRadius: 10, backgroundColor: palette.softCyan }, loading: { minHeight: 64, justifyContent: "center", alignItems: "center", gap: 8 }, muted: { color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: "center" }, error: { color: palette.error, fontSize: 11, lineHeight: 16, backgroundColor: "#FFF0F0", borderRadius: 10, padding: 10 }, tool: { flexDirection: "row", alignItems: "center", gap: 9, padding: 11, borderRadius: 13, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, toolActive: { borderColor: palette.navy, backgroundColor: palette.softCyan }, toolIcon: { width: 32, height: 32, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, toolCopy: { flex: 1, gap: 3 }, toolName: { color: palette.text, fontSize: 12, fontWeight: "800" }, toolDetail: { color: palette.muted, fontSize: 10, lineHeight: 14 }, argsCard: { gap: 9, marginTop: 4 }, label: { color: palette.text, fontSize: 12, fontWeight: "800" }, schema: { color: palette.muted, fontFamily: "monospace", fontSize: 9, lineHeight: 13, backgroundColor: "#F3F7F9", padding: 8, borderRadius: 8 }, input: { minHeight: 96, padding: 10, color: palette.text, fontFamily: "monospace", fontSize: 11, textAlignVertical: "top", borderWidth: 1, borderColor: palette.border, borderRadius: 9 }, run: { height: 43, borderRadius: 11, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 5 }, runText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" } });
