import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { VideoScreenHeader } from "@/components/video-screen-header";
import { palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";

export default function AboutScreen() {
  const links = [{ label: "Link Git", url: "https://github.com/nhut0902-pr/mcp-hub-android" }, { label: "Website", url: "https://mcp-hub-android.vercel.app" }];
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="About" /><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.logo}><MaterialIcons name="hub" color="#FFFFFF" size={48} /></View><Text style={styles.name}>MCP Hub</Text><Text style={styles.version}>V1.0.0</Text><Text style={styles.description}>Một không gian chat tập trung để quản lý provider, model và cấu hình Model Context Protocol trên thiết bị.</Text></View><View style={styles.card}>{links.map((item, index) => <Pressable key={item.label} onPress={() => void Linking.openURL(item.url)} style={[styles.link, index > 0 && styles.divider]}><Text style={styles.linkText}>{item.label}</Text><MaterialIcons name="open-in-new" size={18} color={palette.navy} /></Pressable>)}</View><Text style={styles.team}>Powered By Nhutcoder Team</Text><Text style={styles.foot}>MCP Hub lưu API key vào kho bảo mật của thiết bị; API key AI Cloud được xử lý phía máy chủ.</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, gap: 20 }, hero: { alignItems: "center", gap: 8, paddingTop: 18 }, logo: { width: 90, height: 90, borderRadius: 25, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, name: { color: palette.text, fontSize: 22, fontWeight: "800" }, version: { color: palette.muted, fontSize: 12 }, description: { maxWidth: 300, textAlign: "center", color: "#C7C7C7", fontSize: 12, lineHeight: 18, marginTop: 6 }, card: { borderRadius: 14, backgroundColor: "#242424", borderWidth: 1, borderColor: "#414141" }, link: { minHeight: 49, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 13 }, divider: { borderTopWidth: 1, borderTopColor: "#363636" }, linkText: { color: palette.text, fontSize: 13, fontWeight: "700" }, team: { color: "#89C8FF", fontSize: 12, fontWeight: "800", textAlign: "center", marginBottom: -8 }, foot: { color: palette.muted, fontSize: 11, lineHeight: 16, textAlign: "center" } });
