import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, Linking, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { VideoScreenHeader } from "@/components/video-screen-header";
import { palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { APP_VERSION, checkForAppUpdate, downloadAndInstallAppUpdate, type AppUpdate } from "@/lib/mcp-hub/app-update";

export default function AboutScreen() {
  const links = [{ label: "Link Git", url: "https://github.com/nhut0902-pr/mcp-hub-android" }, { label: "Website", url: "https://mcp-hub-android.vercel.app" }];
  const [checking, setChecking] = useState(false); const [update, setUpdate] = useState<AppUpdate | null>(null); const [progress, setProgress] = useState<number | null>(null);
  const check = async () => { setChecking(true); try { const next = await checkForAppUpdate(); setUpdate(next); if (!next) Alert.alert("MCP Hub đã mới nhất", `Thiết bị đang dùng V${APP_VERSION}.`); } catch (error) { Alert.alert("Không thể kiểm tra cập nhật", error instanceof Error ? error.message : "Hãy thử lại sau."); } finally { setChecking(false); } };
  const install = async () => { if (!update) return; try { setProgress(0); await downloadAndInstallAppUpdate(update, setProgress); } catch (error) { Alert.alert("Không thể cài cập nhật", error instanceof Error ? error.message : "Hãy thử lại sau."); } finally { setProgress(null); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="About" /><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.logo}><MaterialIcons name="hub" color="#FFFFFF" size={48} /></View><Text style={styles.name}>MCP Hub</Text><Text style={styles.version}>V{APP_VERSION}</Text><Text style={styles.description}>Một không gian chat tập trung để quản lý provider, model và cấu hình Model Context Protocol trên thiết bị.</Text></View><View style={styles.card}><Pressable onPress={() => void (update ? install() : check())} disabled={checking || progress !== null} style={styles.link}><View><Text style={styles.linkText}>{progress !== null ? `Đang tải cập nhật ${Math.round(progress * 100)}%` : update ? `Tải và cài V${update.version}` : checking ? "Đang kiểm tra cập nhật…" : "Kiểm tra cập nhật"}</Text><Text style={styles.updateDetail}>{Platform.OS === "android" ? update ? update.notes : "Tải và mở trình cài đặt ngay trong app." : "Tính năng cài APK hỗ trợ Android."}</Text></View><MaterialIcons name={update ? "system-update-alt" : "update"} size={20} color={palette.navy} /></Pressable>{links.map((item, index) => <Pressable key={item.label} onPress={() => void Linking.openURL(item.url)} style={[styles.link, styles.divider, index > 0 && styles.divider]}><Text style={styles.linkText}>{item.label}</Text><MaterialIcons name="open-in-new" size={18} color={palette.navy} /></Pressable>)}</View><Text style={styles.team}>Powered By Nhutcoder Team</Text><Text style={styles.foot}>MCP Hub lưu API key vào kho bảo mật của thiết bị; AI Cloud được xử lý qua lớp bảo mật.</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, gap: 20 }, hero: { alignItems: "center", gap: 8, paddingTop: 18 }, logo: { width: 90, height: 90, borderRadius: 25, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, name: { color: palette.text, fontSize: 22, fontWeight: "800" }, version: { color: palette.muted, fontSize: 12 }, description: { maxWidth: 300, textAlign: "center", color: "#C7C7C7", fontSize: 12, lineHeight: 18, marginTop: 6 }, card: { borderRadius: 14, backgroundColor: "#242424", borderWidth: 1, borderColor: "#414141" }, link: { minHeight: 57, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 13 }, divider: { borderTopWidth: 1, borderTopColor: "#363636" }, linkText: { color: palette.text, fontSize: 13, fontWeight: "700" }, updateDetail: { color: palette.muted, fontSize: 10, lineHeight: 14, marginTop: 3, maxWidth: 250 }, team: { color: "#89C8FF", fontSize: 12, fontWeight: "800", textAlign: "center", marginBottom: -8 }, foot: { color: palette.muted, fontSize: 11, lineHeight: 16, textAlign: "center" } });
