import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AppButton, Card, EmptyState, palette, StatusPill } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { VideoScreenHeader } from "@/components/video-screen-header";
import { useHub } from "@/lib/mcp-hub/context";
import { normaliseModelsResponse } from "@/lib/mcp-hub/model-normalizer";
import { updatePinnedModels } from "@/lib/mcp-hub/pinned-models";
import { listAiCloudModelsFromProxy } from "@/lib/mcp-hub/ai-cloud-client";

export default function AiCloudScreen() {
  const router = useRouter(); const { state, syncingProviderId, syncProvider, saveProvider } = useHub();
  const cloud = state.providers.find((provider) => provider.managedByApp);
  const cloudModels = useMemo(() => cloud ? state.models.filter((model) => model.providerId === cloud.id) : [], [cloud, state.models]);
  const [query, setQuery] = useState(""); const [loadingModels, setLoadingModels] = useState(false);
  const filtered = cloudModels.filter((model) => `${model.displayName} ${model.modelId}`.toLowerCase().includes(query.trim().toLowerCase()));
  const sync = async () => { if (!cloud) return; setLoadingModels(true); try { const data = await listAiCloudModelsFromProxy(); const models = normaliseModelsResponse(data, cloud.id, new Date().toISOString(), cloud.kind); const result = await syncProvider(cloud.id, cloud, models); Alert.alert("AI Cloud đã đồng bộ", `${result.count} model Gemini đã sẵn sàng để ghim vào Chat.`); } catch (error) { Alert.alert("Không thể đồng bộ AI Cloud", error instanceof Error ? error.message : "Có lỗi xảy ra."); } finally { setLoadingModels(false); } };
  const togglePin = async (modelId: string) => { if (!cloud) return; await saveProvider(updatePinnedModels({ ...cloud, pinnedModelIds: cloud.pinnedModelIds }, modelId)); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="AI Cloud" /><View style={styles.content}><Card style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="cloud-done" size={25} color="#FFFFFF" /></View><View style={styles.heroCopy}><View style={styles.heroLine}><Text style={styles.heroTitle}>AI Cloud</Text><StatusPill label="Vercel proxy" tone="success" /></View><Text style={styles.heroDetail}>Gemini và API key được xử lý trên proxy Vercel; API key không hiển thị hoặc lưu trên thiết bị.</Text></View></Card><View style={styles.actionRow}><AppButton label="Đồng bộ model" icon="sync" loading={syncingProviderId === cloud?.id || loadingModels} onPress={() => void sync()} /><AppButton label="Mở Chat" icon="chat" variant="secondary" onPress={() => router.replace("/chat")} /></View><View style={styles.sectionLine}><Text style={styles.section}>Models</Text><Text style={styles.count}>{cloudModels.length} model</Text></View><View style={styles.search}><MaterialIcons name="search" color="#A5A5A5" size={19} /><TextInput value={query} onChangeText={setQuery} placeholder="Tìm model AI Cloud" placeholderTextColor="#8E8E8E" style={styles.searchInput} /></View><FlatList data={filtered} keyExtractor={(model) => model.id} contentContainerStyle={styles.list} renderItem={({ item }) => <Card style={styles.model}><View style={styles.modelCopy}><Text style={styles.modelName}>{item.displayName}</Text><Text style={styles.modelId} numberOfLines={1}>{item.modelId}</Text><View style={styles.modelMeta}>{item.supportsThinking ? <StatusPill label="Thinking" tone="success" /> : null}{item.supportsWebSearch ? <StatusPill label="Web" /> : null}</View></View><Pressable onPress={() => void togglePin(item.modelId)} style={[styles.pin, cloud?.pinnedModelIds.includes(item.modelId) && styles.pinActive]}><MaterialIcons name="push-pin" color={cloud?.pinnedModelIds.includes(item.modelId) ? "#FFFFFF" : palette.navy} size={18} /><Text style={[styles.pinText, cloud?.pinnedModelIds.includes(item.modelId) && styles.pinTextActive]}>{cloud?.pinnedModelIds.includes(item.modelId) ? "Đã ghim" : "Ghim"}</Text></Pressable></Card>} ListEmptyComponent={<EmptyState icon="cloud-sync" title="Chưa có model AI Cloud" detail="Chạm Đồng bộ model để lấy Gemini từ proxy Vercel." />} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { flex: 1, padding: 14, gap: 11 }, hero: { flexDirection: "row", gap: 11, backgroundColor: "#243545", borderColor: "#416179" }, heroIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, heroCopy: { flex: 1, gap: 4 }, heroLine: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" }, heroTitle: { color: palette.text, fontSize: 15, fontWeight: "800" }, heroDetail: { color: "#BDD8EE", fontSize: 11, lineHeight: 16 }, actionRow: { flexDirection: "row", gap: 8 }, sectionLine: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4 }, section: { color: palette.text, fontSize: 13, fontWeight: "800" }, count: { color: palette.muted, fontSize: 11 }, search: { height: 41, backgroundColor: "#2B2B2B", borderWidth: 1, borderColor: "#464646", borderRadius: 10, paddingHorizontal: 10, gap: 8, flexDirection: "row", alignItems: "center" }, searchInput: { flex: 1, color: palette.text, fontSize: 12 }, list: { gap: 7, paddingBottom: 16 }, model: { padding: 10, flexDirection: "row", alignItems: "center", gap: 8 }, modelCopy: { flex: 1, gap: 3 }, modelName: { color: palette.text, fontSize: 13, fontWeight: "800" }, modelId: { color: palette.muted, fontSize: 10, fontFamily: "monospace" }, modelMeta: { flexDirection: "row", gap: 5, marginTop: 3 }, pin: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 8, backgroundColor: "#213C53", gap: 4, alignItems: "center" }, pinActive: { backgroundColor: palette.navy }, pinText: { color: "#BFE1FF", fontSize: 10, fontWeight: "800" }, pinTextActive: { color: "#FFFFFF" } });
