import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as ImagePicker from "expo-image-picker";
import { useMemo, useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AiMathGraph } from "@/components/ai-math-graph";
import { AppButton, Card, palette, StatusPill } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { VideoScreenHeader } from "@/components/video-screen-header";
import { comparatorLabel, kindLabel, parseInequalitySystem, type ParsedInequality } from "@/lib/ai-math/inequality";
import { sendAiCloudChatFromProxy } from "@/lib/mcp-hub/ai-cloud-client";
import { parseChatCompletion } from "@/lib/mcp-hub/chat";

const examples = ["2x + y ≤ 6", "y ≥ x^2 - 4", "y ≤ |x| + 2", "x^2 + y^2 ≤ 25", "x + y ≤ 6; x ≥ 0; y ≥ 0"];
export default function AiMathScreen() {
  const [formula, setFormula] = useState(examples[0]); const [inequalities, setInequalities] = useState<ParsedInequality[]>(() => parseInequalitySystem(examples[0])); const [solution, setSolution] = useState(""); const [photoUri, setPhotoUri] = useState<string | null>(null); const [readingPhoto, setReadingPhoto] = useState(false);
  const summary = useMemo(() => inequalities.length === 1 ? `${kindLabel(inequalities[0])} · biên ${comparatorLabel(inequalities[0].comparator)}` : `Hệ ${inequalities.length} bất phương trình`, [inequalities]);
  const draw = () => { try { setInequalities(parseInequalitySystem(formula)); } catch (error) { Alert.alert("Không đọc được miền nghiệm", error instanceof Error ? error.message : "Nhập bất phương trình hợp lệ, ví dụ x + y <= 6; x >= 0."); } };
  const readProblemImage = async (source: "camera" | "library") => { setReadingPhoto(true); try { if (source === "camera") { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (permission.status !== "granted") throw new Error("Cần quyền Camera để chụp bài toán. Hãy cấp quyền rồi thử lại."); } const result = source === "camera" ? await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], quality: 0.65, base64: true }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.65, base64: true }); if (result.canceled) return; const asset = result.assets[0]; const imageUrl = asset.base64 ? `data:${asset.mimeType ?? "image/jpeg"};base64,${asset.base64}` : asset.uri; if (!imageUrl) throw new Error("Không đọc được ảnh. Hãy thử chụp lại ảnh rõ, đủ sáng và thẳng trang."); setPhotoUri(asset.uri); const response = await sendAiCloudChatFromProxy({ model: "gemini-1.5-flash", temperature: 0.1, max_tokens: 900, messages: [{ role: "user", content: [{ type: "text", text: "Đọc đề toán trong ảnh. Nếu có bất phương trình hoặc hệ bất phương trình, trả dòng đầu tiên là công thức vẽ được: dùng x,y, <=, >=, <, > và ngăn hệ bằng dấu ;. Sau đó giải thích ngắn bằng tiếng Việt. Nếu ảnh không rõ, nói rõ phần cần chụp lại." }, { type: "image_url", image_url: { url: imageUrl } }] }] }); const answer = parseChatCompletion(response).content.trim(); const candidate = answer.split("\n").map((line) => line.replace(/^.*?:\s*/, "").trim()).find((line) => /[xy].*(<=|>=|≤|≥|<|>)/i.test(line)); setSolution(answer || "AI không trả nội dung. Hãy thử ảnh rõ hơn."); if (candidate) { setFormula(candidate); setInequalities(parseInequalitySystem(candidate)); } } catch (error) { Alert.alert("Không đọc được ảnh bài toán", error instanceof Error ? error.message : "Hãy thử ảnh rõ hơn hoặc nhập công thức bằng tay."); } finally { setReadingPhoto(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="AI Math" /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Card style={styles.hero}><View style={styles.icon}><MaterialIcons name="functions" size={25} color="#FFFFFF" /></View><View style={styles.heroCopy}><View style={styles.titleLine}><Text style={styles.title}>AI Math</Text><StatusPill label="Graph" tone="success" /></View><Text style={styles.detail}>Nhập, chụp hoặc chọn ảnh đề để AI nhận công thức, giải và vẽ miền nghiệm.</Text></View></Card><View style={styles.photoActions}><AppButton label="Chụp bài toán" icon="photo-camera" variant="secondary" loading={readingPhoto} onPress={() => void readProblemImage("camera")} /><AppButton label="Chọn ảnh đề" icon="image" variant="secondary" loading={readingPhoto} onPress={() => void readProblemImage("library")} /></View>{photoUri ? <Image source={{ uri: photoUri }} style={styles.photoPreview} /> : null}<View style={styles.field}><Text style={styles.label}>Bất phương trình</Text><TextInput value={formula} onChangeText={setFormula} onSubmitEditing={draw} returnKeyType="done" autoCapitalize="none" autoCorrect={false} multiline style={styles.input} placeholder="Ví dụ: x + y ≤ 6; x ≥ 0; y ≥ 0" placeholderTextColor="#87929E" /></View><View style={styles.examples}>{examples.map((item) => <Pressable key={item} onPress={() => { setFormula(item); setInequalities(parseInequalitySystem(item)); }} style={({ pressed }) => [styles.example, { opacity: pressed ? 0.7 : 1 }]}><Text style={styles.exampleText}>{item}</Text></Pressable>)}</View><AppButton label="Vẽ miền nghiệm" icon="query-stats" onPress={draw} /><Card style={styles.graphCard}><View style={styles.graphHeading}><View><Text style={styles.graphTitle}>Miền nghiệm</Text><Text style={styles.formula}>{formula}</Text></View><StatusPill label={summary} tone="neutral" /></View><AiMathGraph inequalities={inequalities} /><View style={styles.legend}><View style={styles.legendItem}><View style={styles.fillDot} /><Text style={styles.legendText}>Miền thỏa mãn</Text></View><View style={styles.legendItem}><View style={styles.lineDot} /><Text style={styles.legendText}>Đường biên</Text></View></View></Card><Card style={styles.help}><Text style={styles.helpTitle}>Dạng được hỗ trợ</Text><Text style={styles.helpText}>Nhập một BPT hoặc hệ bằng dấu chấm phẩy/xuống dòng. Hỗ trợ tuyến tính, parabol, trị tuyệt đối và đường tròn; dấu nghiêm dùng biên nét đứt.</Text></Card>{solution ? <Card style={styles.solution}><View style={styles.solutionHead}><MaterialIcons name="auto-awesome" size={17} color="#8D6FE9" /><Text style={styles.solutionTitle}>AI Math giải bài</Text></View><Text style={styles.solutionText}>{solution}</Text></Card> : null}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 14, paddingBottom: 30, gap: 12 }, hero: { flexDirection: "row", gap: 11, backgroundColor: "#243545", borderColor: "#416179" }, icon: { width: 44, height: 44, borderRadius: 14, backgroundColor: "#805BD7", justifyContent: "center", alignItems: "center" }, heroCopy: { flex: 1, gap: 4 }, titleLine: { flexDirection: "row", alignItems: "center", gap: 8 }, title: { color: palette.text, fontSize: 15, fontWeight: "800" }, detail: { color: "#BDD8EE", fontSize: 11, lineHeight: 16 }, photoActions: { flexDirection: "row", gap: 8 }, photoPreview: { height: 170, width: "100%", borderRadius: 13, resizeMode: "cover", borderWidth: 1, borderColor: "#4F5F70" }, field: { gap: 6 }, label: { color: palette.text, fontWeight: "800", fontSize: 12 }, input: { minHeight: 48, borderWidth: 1, borderColor: "#454B55", borderRadius: 12, backgroundColor: "#282C32", color: palette.text, paddingHorizontal: 13, fontSize: 15, fontWeight: "700" }, examples: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, example: { borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7, backgroundColor: "#29333E", borderWidth: 1, borderColor: "#3D5368" }, exampleText: { color: "#BFE1FF", fontSize: 10, fontWeight: "700" }, graphCard: { gap: 12 }, graphHeading: { flexDirection: "row", justifyContent: "space-between", gap: 10, alignItems: "flex-start" }, graphTitle: { color: palette.text, fontSize: 14, fontWeight: "800" }, formula: { color: palette.muted, fontFamily: "monospace", fontSize: 11, marginTop: 3 }, legend: { flexDirection: "row", flexWrap: "wrap", gap: 14 }, legendItem: { flexDirection: "row", gap: 6, alignItems: "center" }, fillDot: { width: 11, height: 11, borderRadius: 3, backgroundColor: "#2996F3", opacity: 0.5 }, lineDot: { width: 14, height: 2, backgroundColor: "#FFB35C" }, legendText: { color: palette.muted, fontSize: 10 }, help: { gap: 5 }, helpTitle: { color: palette.text, fontSize: 12, fontWeight: "800" }, helpText: { color: palette.muted, fontSize: 10, lineHeight: 15 }, solution: { gap: 7, backgroundColor: "#28243A", borderColor: "#645493" }, solutionHead: { flexDirection: "row", alignItems: "center", gap: 7 }, solutionTitle: { color: "#D8CDFF", fontSize: 12, fontWeight: "800" }, solutionText: { color: "#E4DFFC", fontSize: 11, lineHeight: 17 } });
