import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppButton, Card, EmptyState, palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { VideoScreenHeader } from "@/components/video-screen-header";
import { ArchivedChat, clearArchivedChats, loadArchivedChats, removeArchivedChat } from "@/lib/mcp-hub/chat-archive";

export default function ArchivedChatsScreen() {
  const router = useRouter(); const [items, setItems] = useState<ArchivedChat[]>([]);
  const refresh = useCallback(() => { void loadArchivedChats().then(setItems); }, []); useFocusEffect(refresh);
  const clearAll = () => Alert.alert("Xoá kho lưu trữ", "Xoá vĩnh viễn mọi hội thoại đã lưu?", [{ text: "Huỷ", style: "cancel" }, { text: "Xoá", style: "destructive", onPress: () => { void clearArchivedChats().then(refresh); } }]);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="Archived Chats" /><View style={styles.content}>{items.length ? <View style={styles.actions}><Text style={styles.count}>{items.length} hội thoại đã lưu</Text><AppButton label="Xoá tất cả" icon="delete-outline" variant="danger" onPress={clearAll} /></View> : null}<FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => { const preview = item.messages.find((message) => message.content.trim())?.content ?? "Không có nội dung"; return <Card style={styles.card}><Pressable onPress={() => router.push({ pathname: "/chat", params: { archiveId: item.id } } as never)} style={styles.cardCopy}><View style={styles.icon}><MaterialIcons name="inventory-2" size={20} color="#FFFFFF" /></View><View style={styles.texts}><Text style={styles.name} numberOfLines={1}>{item.name}</Text><Text style={styles.preview} numberOfLines={2}>{preview}</Text><Text style={styles.date}>{new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(item.savedAt))}</Text></View><MaterialIcons name="chevron-right" size={21} color="#A5A5A5" /></Pressable><Pressable onPress={() => void removeArchivedChat(item.id).then(setItems)} style={styles.delete}><MaterialIcons name="delete-outline" size={18} color={palette.error} /></Pressable></Card>; }} ListEmptyComponent={<EmptyState icon="inventory-2" title="Chưa có hội thoại đã lưu" detail="Trong Chat, mở menu ba chấm rồi chọn Archive Chat để lưu cuộc hội thoại hiện tại." />} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { flex: 1, padding: 14 }, actions: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 9 }, count: { color: palette.muted, fontSize: 11 }, list: { gap: 8, paddingBottom: 20 }, card: { padding: 10, flexDirection: "row", gap: 8, alignItems: "center" }, cardCopy: { flex: 1, flexDirection: "row", gap: 9, alignItems: "center" }, icon: { width: 37, height: 37, borderRadius: 11, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center", alignSelf: "flex-start" }, texts: { flex: 1, gap: 2 }, name: { color: palette.text, fontSize: 13, fontWeight: "800" }, preview: { color: palette.muted, fontSize: 11, lineHeight: 15 }, date: { color: "#7E7E7E", fontSize: 9, marginTop: 2 }, delete: { width: 34, height: 34, alignItems: "center", justifyContent: "center" } });
