import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { VideoScreenHeader } from "@/components/video-screen-header";
import { palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";

const toggles = ["Hiển thị avatar", "Render Markdown", "Hiển thị reasoning", "Hiển thị thời gian phản hồi"];
export default function ChatSettingsScreen() {
  const [values, setValues] = useState<Record<string, boolean>>({ "Hiển thị avatar": true, "Render Markdown": true, "Hiển thị reasoning": true, "Hiển thị thời gian phản hồi": false });
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="Chat Settings" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.description}>Tuỳ chỉnh cách hiển thị hội thoại, bong bóng chat và nội dung phản hồi AI.</Text><Text style={styles.section}>Appearance</Text><View style={styles.card}><View style={styles.preview}><View style={[styles.avatar, { backgroundColor: "#FF7B39" }]}><MaterialIcons name="smart-toy" size={16} color="#FFFFFF" /></View><View style={styles.aiBubble}><Text style={styles.aiText}>Đây là phản hồi AI có Markdown.</Text></View></View><View style={[styles.preview, { justifyContent: "flex-end" }]}><View style={styles.userBubble}><Text style={styles.userText}>Tin nhắn của bạn</Text></View></View></View><Text style={styles.section}>Display</Text><View style={styles.card}>{toggles.map((label, index) => <View key={label} style={[styles.row, index < toggles.length - 1 && styles.divider]}><View style={styles.rowIcon}><MaterialIcons name={index === 1 ? "article" : index === 2 ? "psychology" : "visibility"} size={19} color="#CFCFCF" /></View><Text style={styles.rowText}>{label}</Text><Switch value={values[label]} onValueChange={(value) => setValues((current) => ({ ...current, [label]: value }))} trackColor={{ false: "#4B4B4B", true: palette.navy }} thumbColor="#F4F4F4" /></View>)}</View><Text style={styles.section}>Message style</Text><View style={styles.card}><View style={styles.row}><Text style={styles.rowText}>User bubble</Text><View style={styles.colorDot} /></View><View style={[styles.row, styles.divider]}><Text style={styles.rowText}>Assistant bubble</Text><View style={[styles.colorDot, { backgroundColor: "#383838" }]} /></View><View style={[styles.row, styles.divider]}><Text style={styles.rowText}>System prompt</Text><View style={[styles.colorDot, { backgroundColor: "#FF7B39" }]} /></View></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 15, paddingBottom: 32, gap: 10 }, description: { color: palette.muted, fontSize: 12, lineHeight: 18 }, section: { color: palette.text, fontSize: 13, fontWeight: "800", marginTop: 8 }, card: { backgroundColor: "#242424", borderWidth: 1, borderColor: "#414141", borderRadius: 14, padding: 12, gap: 10 }, preview: { flexDirection: "row", alignItems: "flex-end", gap: 8 }, avatar: { width: 27, height: 27, borderRadius: 14, alignItems: "center", justifyContent: "center" }, aiBubble: { backgroundColor: "#383838", borderRadius: 12, borderBottomLeftRadius: 4, paddingHorizontal: 10, paddingVertical: 8 }, aiText: { color: palette.text, fontSize: 12 }, userBubble: { backgroundColor: palette.navy, borderRadius: 12, borderBottomRightRadius: 4, paddingHorizontal: 10, paddingVertical: 8 }, userText: { color: "#FFFFFF", fontSize: 12 }, row: { minHeight: 43, flexDirection: "row", alignItems: "center", gap: 10 }, divider: { borderTopWidth: 1, borderTopColor: "#363636" }, rowIcon: { width: 22, alignItems: "center" }, rowText: { flex: 1, color: "#E0E0E0", fontSize: 13 }, colorDot: { width: 22, height: 22, borderRadius: 11, backgroundColor: palette.navy, borderWidth: 2, borderColor: "#707070" } });
