import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { VideoScreenHeader } from "@/components/video-screen-header";
import { palette, StatusPill } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";

const COPILOTS = [{ name: "Research Assistant", description: "Tổng hợp câu trả lời với web search và nguồn trích dẫn.", icon: "travel-explore", tag: "Research" }, { name: "MCP Config Helper", description: "Hỗ trợ thiết lập provider, model và profile MCP an toàn.", icon: "hub", tag: "Professional Skills" }, { name: "Code Reviewer", description: "Phân tích đoạn mã và gợi ý cải thiện theo ngữ cảnh cuộc trò chuyện.", icon: "code", tag: "Development" }];
export default function CopilotsScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="My Copilots" /><ScrollView contentContainerStyle={styles.content}>{COPILOTS.map((copilot) => <View key={copilot.name} style={styles.card}><View style={styles.icon}><MaterialIcons name={copilot.icon as keyof typeof MaterialIcons.glyphMap} size={22} color="#FFFFFF" /></View><View style={styles.copy}><Text style={styles.name}>{copilot.name}</Text><Text style={styles.description}>{copilot.description}</Text><StatusPill label={copilot.tag} tone="success" /></View><MaterialIcons name="chevron-right" size={21} color="#999999" /></View>)}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 15, gap: 10, paddingBottom: 30 }, card: { minHeight: 110, backgroundColor: "#242424", borderRadius: 15, borderWidth: 1, borderColor: "#414141", padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, icon: { width: 41, height: 41, borderRadius: 13, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center", alignSelf: "flex-start" }, copy: { flex: 1, gap: 6 }, name: { color: palette.text, fontSize: 14, fontWeight: "800" }, description: { color: palette.muted, fontSize: 11, lineHeight: 16 } });
