import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppButton, Card, EmptyState, palette, StatusPill } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { VideoScreenHeader } from "@/components/video-screen-header";

type ParsedDocument = { name: string; mimeType: string | null; size: number | null; excerpt: string; status: "parsed" | "metadata" };
const TEXT_TYPES = ["text/plain", "text/markdown", "application/json", "text/csv"];
export default function DocumentParserScreen() {
  const [document, setDocument] = useState<ParsedDocument | null>(null); const [processing, setProcessing] = useState(false);
  const pick = async () => { setProcessing(true); try { const result = await DocumentPicker.getDocumentAsync({ type: ["text/plain", "text/markdown", "application/json", "text/csv", "application/pdf"], copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; const readable = TEXT_TYPES.includes(asset.mimeType ?? "") || /\.(txt|md|json|csv)$/i.test(asset.name); const excerpt = readable ? (await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.UTF8 })).replace(/\s+/g, " ").trim().slice(0, 1600) || "Tệp trống hoặc không có ký tự văn bản." : "Đã nhận metadata tệp. Phiên bản hiện tại trích xuất trực tiếp văn bản thuần (.txt, .md, .json, .csv); PDF được giữ để đính kèm vào Chat."; setDocument({ name: asset.name, mimeType: asset.mimeType ?? null, size: asset.size ?? null, excerpt, status: readable ? "parsed" : "metadata" }); } catch (error) { Alert.alert("Không thể đọc tài liệu", error instanceof Error ? error.message : "Có lỗi xảy ra khi chọn tệp."); } finally { setProcessing(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="Document Parser" /><ScrollView contentContainerStyle={styles.content}>{document ? <><Card style={styles.fileCard}><View style={styles.fileIcon}><MaterialIcons name="description" color="#FFFFFF" size={24} /></View><View style={styles.fileCopy}><Text style={styles.fileName} numberOfLines={1}>{document.name}</Text><Text style={styles.meta}>{document.mimeType ?? "Không rõ định dạng"}{document.size ? ` · ${(document.size / 1024).toFixed(1)} KB` : ""}</Text><StatusPill label={document.status === "parsed" ? "Đã trích xuất" : "Metadata"} tone={document.status === "parsed" ? "success" : "warning"} /></View><Pressable onPress={() => setDocument(null)}><MaterialIcons name="close" color="#B8B8B8" size={21} /></Pressable></Card><Text style={styles.section}>Nội dung trích xuất</Text><Card style={styles.excerpt}><Text style={styles.excerptText}>{document.excerpt}</Text></Card><AppButton label="Chọn tài liệu khác" icon="upload-file" onPress={() => void pick()} loading={processing} /></> : <><Card><EmptyState icon="description" title="Chưa chọn tài liệu" detail="Chọn .txt, .md, .json, .csv hoặc PDF. Văn bản được trích xuất cục bộ trên thiết bị; PDF sẽ giữ metadata để đính kèm vào Chat." /></Card><AppButton label="Chọn tài liệu" icon="upload-file" onPress={() => void pick()} loading={processing} /></>}<Card style={styles.note}><MaterialIcons name="privacy-tip" color="#6DBBFF" size={18} /><Text style={styles.noteText}>Nội dung văn bản chỉ được đọc trên thiết bị cho đến khi bạn chủ động đính kèm hoặc gửi trong Chat.</Text></Card></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 14, gap: 10, paddingBottom: 28 }, fileCard: { flexDirection: "row", alignItems: "center", gap: 10 }, fileIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: palette.navy }, fileCopy: { flex: 1, gap: 4 }, fileName: { color: palette.text, fontSize: 13, fontWeight: "800" }, meta: { color: palette.muted, fontSize: 10 }, section: { color: palette.text, fontSize: 13, fontWeight: "800", marginTop: 4 }, excerpt: { backgroundColor: "#242424" }, excerptText: { color: "#D4D4D4", fontSize: 12, lineHeight: 18 }, note: { flexDirection: "row", gap: 8, backgroundColor: "#213C53", borderColor: "#416179" }, noteText: { flex: 1, color: "#BFE1FF", fontSize: 11, lineHeight: 16 } });
