import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AppButton, Card, palette, StatusPill } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { VideoScreenHeader } from "@/components/video-screen-header";
import { sendAiCloudChatFromProxy } from "@/lib/mcp-hub/ai-cloud-client";
import { parseChatCompletion } from "@/lib/mcp-hub/chat";
import { createStudyDeck, dueCards, loadStudyDecks, parseFlashcardDrafts, rateStudyCard, removeStudyDeck, saveStudyDecks, type ReviewRating, type StudyDeck } from "@/lib/study/flashcards";

export default function FlashcardsScreen() {
  const params = useLocalSearchParams<{ source?: string; title?: string }>(); const [decks, setDecks] = useState<StudyDeck[]>([]); const [source, setSource] = useState(typeof params.source === "string" ? params.source : ""); const [title, setTitle] = useState(typeof params.title === "string" ? params.title : ""); const [creating, setCreating] = useState(false); const [activeDeck, setActiveDeck] = useState<StudyDeck | null>(null); const [cardIndex, setCardIndex] = useState(0); const [revealed, setRevealed] = useState(false);
  useEffect(() => { void loadStudyDecks().then(setDecks); }, []);
  const activeCards = useMemo(() => activeDeck ? (dueCards(activeDeck).length ? dueCards(activeDeck) : activeDeck.cards) : [], [activeDeck]); const activeCard = activeCards[cardIndex];
  const createWithAi = async () => { const material = source.trim(); if (!material || creating) return; setCreating(true); try { const response = await sendAiCloudChatFromProxy({ model: "gemini-1.5-flash", temperature: 0.25, max_tokens: 1800, messages: [{ role: "system", content: "Bạn tạo Flashcard học tập bằng tiếng Việt. Chỉ trả JSON hợp lệ, không Markdown: {\"title\":\"...\",\"cards\":[{\"front\":\"câu hỏi ngắn\",\"back\":\"đáp án chính xác, súc tích\",\"hint\":\"gợi ý tùy chọn\"}]}. Tạo 6 đến 12 thẻ. Không bịa kiến thức ngoài nguồn; nếu nguồn không đủ, tạo ít thẻ và nói rõ bằng JSON vẫn hợp lệ." }, { role: "user", content: material }] }); const draft = parseFlashcardDrafts(parseChatCompletion(response).content); if (!draft) throw new Error("AI không trả bộ Flashcard đúng định dạng. Hãy bổ sung nguồn hoặc thử lại."); const deck = createStudyDeck(title || draft.title || "Flashcard AI", material, draft.cards); const next = [deck, ...decks]; setDecks(next); await saveStudyDecks(next); setSource(""); setTitle(""); Alert.alert("Đã tạo Flashcard", `Đã lưu ${deck.cards.length} thẻ để ôn tập cục bộ.`); } catch (error) { Alert.alert("Không thể tạo Flashcard", error instanceof Error ? error.message : "Lỗi không xác định"); } finally { setCreating(false); } };
  const openDeck = (deck: StudyDeck) => { setActiveDeck(deck); setCardIndex(0); setRevealed(false); };
  const rate = async (rating: ReviewRating) => { if (!activeDeck || !activeCard) return; const card = rateStudyCard(activeCard, rating); const updated = { ...activeDeck, updatedAt: Date.now(), cards: activeDeck.cards.map((item) => item.id === card.id ? card : item) }; const next = decks.map((item) => item.id === updated.id ? updated : item); setDecks(next); setActiveDeck(updated); await saveStudyDecks(next); const nextCards = dueCards(updated).length ? dueCards(updated) : updated.cards; if (cardIndex + 1 >= nextCards.length) { setActiveDeck(null); Alert.alert("Hoàn tất phiên ôn", "Tiến độ đã được lưu cục bộ."); } else { setCardIndex((value) => value + 1); setRevealed(false); } };
  if (activeDeck && activeCard) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="Ôn Flashcard" backTo="/flashcards" /><View style={styles.study}><Text style={styles.progress}>{cardIndex + 1} / {activeCards.length} · {activeDeck.title}</Text><Pressable onPress={() => setRevealed((value) => !value)} style={styles.flashcard}><Text style={styles.side}>{revealed ? "Đáp án" : "Câu hỏi"}</Text><Text style={styles.cardText}>{revealed ? activeCard.back : activeCard.front}</Text>{revealed && activeCard.hint ? <Text style={styles.hint}>Gợi ý: {activeCard.hint}</Text> : <Text style={styles.tap}>Chạm để {revealed ? "xem lại câu hỏi" : "lật thẻ"}</Text>}</Pressable>{revealed ? <View style={styles.ratings}><AppButton label="Cần ôn lại" icon="replay" variant="secondary" onPress={() => void rate("again")} /><AppButton label="Ổn" icon="done" variant="secondary" onPress={() => void rate("good")} /><AppButton label="Đã thuộc" icon="bolt" onPress={() => void rate("easy")} /></View> : null}</View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="Flashcard AI" backTo="/copilots" /><FlatList data={decks} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.headerContent}><Card style={styles.hero}><View style={styles.icon}><MaterialIcons name="style" size={23} color="#FFFFFF" /></View><View style={{ flex: 1 }}><View style={styles.titleLine}><Text style={styles.title}>Ghi nhớ chủ động</Text><StatusPill label="Local" tone="success" /></View><Text style={styles.detail}>Dán chủ đề, ghi chú hoặc lời giải. AI tạo bộ thẻ, còn lịch ôn được lưu riêng trên thiết bị.</Text></View></Card><View style={styles.field}><Text style={styles.label}>Tên bộ thẻ</Text><TextInput value={title} onChangeText={setTitle} style={styles.titleInput} placeholder="Ví dụ: Sinh học chương 3" placeholderTextColor="#8B99A5" /></View><View style={styles.field}><Text style={styles.label}>Nguồn học</Text><TextInput value={source} onChangeText={setSource} style={styles.sourceInput} multiline textAlignVertical="top" placeholder="Dán kiến thức, khái niệm, lời giải từ AI Gia sư hoặc nội dung muốn ôn…" placeholderTextColor="#8B99A5" /></View><AppButton label={creating ? "Đang tạo Flashcard…" : "Tạo bộ thẻ với AI"} icon="auto-awesome" loading={creating} disabled={!source.trim()} onPress={() => void createWithAi()} /><Text style={styles.listTitle}>Bộ thẻ của bạn</Text></View>} renderItem={({ item }) => <Pressable onPress={() => openDeck(item)} style={({ pressed }) => [styles.deck, { opacity: pressed ? 0.75 : 1 }]}><View style={styles.deckIcon}><MaterialIcons name="style" size={19} color="#B8D8FF" /></View><View style={{ flex: 1 }}><Text style={styles.deckTitle}>{item.title}</Text><Text numberOfLines={1} style={styles.deckMeta}>{item.cards.length} thẻ · {dueCards(item).length} thẻ cần ôn</Text></View><Pressable hitSlop={10} onPress={() => Alert.alert("Xoá bộ thẻ", `Xoá “${item.title}” khỏi thiết bị?`, [{ text: "Huỷ", style: "cancel" }, { text: "Xoá", style: "destructive", onPress: () => void removeStudyDeck(item.id).then(setDecks) }])}><MaterialIcons name="delete-outline" size={20} color="#E99A9A" /></Pressable><MaterialIcons name="chevron-right" size={21} color="#AAB9C5" /></Pressable>} ListEmptyComponent={<Card style={styles.empty}><MaterialIcons name="style" size={29} color="#638FB1" /><Text style={styles.emptyTitle}>Chưa có Flashcard</Text><Text style={styles.emptyDetail}>Tạo bộ thẻ đầu tiên từ một chủ đề, ghi chú hoặc lời giải ở trên.</Text></Card>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 14, paddingBottom: 32, gap: 10 }, headerContent: { gap: 12, paddingBottom: 6 }, hero: { flexDirection: "row", gap: 11, backgroundColor: "#233446", borderColor: "#3E6688" }, icon: { width: 43, height: 43, borderRadius: 14, justifyContent: "center", alignItems: "center", backgroundColor: "#2E75A6" }, titleLine: { flexDirection: "row", gap: 8, alignItems: "center" }, title: { color: palette.text, fontSize: 15, fontWeight: "800" }, detail: { color: "#C4DBEE", fontSize: 11, lineHeight: 16, marginTop: 4 }, field: { gap: 6 }, label: { color: palette.text, fontSize: 12, fontWeight: "800" }, titleInput: { height: 46, borderRadius: 11, borderWidth: 1, borderColor: "#43596A", paddingHorizontal: 12, color: palette.text, backgroundColor: "#172127", fontSize: 13 }, sourceInput: { minHeight: 120, borderRadius: 12, borderWidth: 1, borderColor: "#43596A", padding: 12, color: palette.text, backgroundColor: "#172127", fontSize: 13, lineHeight: 19 }, listTitle: { color: palette.text, fontSize: 14, fontWeight: "800", marginTop: 3 }, deck: { flexDirection: "row", gap: 10, alignItems: "center", padding: 12, borderRadius: 13, borderWidth: 1, borderColor: "#3B4E5A", backgroundColor: "#222C33" }, deckIcon: { width: 36, height: 36, borderRadius: 11, justifyContent: "center", alignItems: "center", backgroundColor: "#23445B" }, deckTitle: { color: palette.text, fontSize: 13, fontWeight: "800" }, deckMeta: { color: palette.muted, fontSize: 10, marginTop: 4 }, empty: { alignItems: "center", paddingVertical: 28, gap: 7, backgroundColor: "#20272B" }, emptyTitle: { color: palette.text, fontSize: 13, fontWeight: "800" }, emptyDetail: { color: palette.muted, textAlign: "center", fontSize: 11, lineHeight: 16, maxWidth: 260 }, study: { flex: 1, padding: 16, gap: 14 }, progress: { color: "#A8C8DF", fontSize: 11, fontWeight: "700", textAlign: "center" }, flashcard: { flex: 1, minHeight: 330, borderRadius: 22, padding: 24, justifyContent: "center", backgroundColor: "#203040", borderWidth: 1, borderColor: "#436D8B" }, side: { color: "#88C9FF", fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 18 }, cardText: { color: "#F0F7FC", fontSize: 20, lineHeight: 29, fontWeight: "700" }, hint: { color: "#C8DDEB", fontSize: 12, lineHeight: 18, marginTop: 21 }, tap: { color: "#AABCC8", fontSize: 11, marginTop: 24 }, ratings: { gap: 9 } });
