import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { VideoScreenHeader } from "@/components/video-screen-header";
import { palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { DEFAULT_GENERAL_SETTINGS, loadGeneralSettings, saveGeneralSettings, type GeneralSettings } from "@/lib/mcp-hub/feature-settings";

export default function GeneralSettingsScreen() {
  const [settings, setSettings] = useState<GeneralSettings>(DEFAULT_GENERAL_SETTINGS); const [saved, setSaved] = useState(false);
  useEffect(() => { void loadGeneralSettings().then(setSettings); }, []);
  const change = async (next: GeneralSettings) => { setSettings(next); setSaved(false); await saveGeneralSettings(next); setSaved(true); };
  const selection = (title: string, value: string, choices: { label: string; value: string }[], select: (value: string) => void) => <View style={styles.card}><Text style={styles.label}>{title}</Text><View style={styles.options}>{choices.map((choice) => <Pressable key={choice.value} onPress={() => select(choice.value)} style={[styles.option, value === choice.value && [styles.optionActive, { backgroundColor: settings.accent }]]}><Text style={[styles.optionText, value === choice.value && styles.optionTextActive]}>{choice.label}</Text></Pressable>)}</View></View>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="General Settings" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.description}>Tuỳ chọn được lưu cục bộ trên thiết bị và được dùng khi mở lại MCP Hub.</Text><Text style={styles.section}>Appearance</Text>{selection("Theme", settings.theme, [{ label: "Light", value: "light" }, { label: "Dark", value: "dark" }, { label: "System", value: "system" }], (theme) => void change({ ...settings, theme: theme as GeneralSettings["theme"] }))}{selection("Font size", settings.fontSize, [{ label: "Small", value: "small" }, { label: "Medium", value: "medium" }, { label: "Large", value: "large" }], (fontSize) => void change({ ...settings, fontSize: fontSize as GeneralSettings["fontSize"] }))}<View style={styles.card}><Text style={styles.label}>Primary color</Text><View style={styles.colors}>{["#2996F3", "#8B5CF6", "#00A87A", "#FF7B39"].map((color) => <Pressable key={color} onPress={() => void change({ ...settings, accent: color })} style={[styles.swatch, { backgroundColor: color }, settings.accent === color && styles.swatchActive]}><MaterialIcons name="check" color="#FFFFFF" size={16} style={{ opacity: settings.accent === color ? 1 : 0 }} /></Pressable>)}</View></View><Text style={styles.section}>Language</Text><View style={styles.card}><View style={styles.row}><MaterialIcons name="language" size={20} color="#D0D0D0" /><Text style={styles.rowText}>Tiếng Việt</Text><MaterialIcons name="check" size={19} color={settings.accent} /></View></View>{saved ? <View style={styles.saved}><MaterialIcons name="check-circle" size={16} color={palette.success} /><Text style={styles.savedText}>Đã lưu vào thiết bị</Text></View> : null}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 15, paddingBottom: 32, gap: 10 }, description: { color: palette.muted, fontSize: 12, lineHeight: 18 }, section: { color: palette.text, fontSize: 13, fontWeight: "800", marginTop: 8 }, card: { backgroundColor: "#242424", borderWidth: 1, borderColor: "#414141", borderRadius: 14, padding: 12, gap: 9 }, label: { color: "#E2E2E2", fontSize: 12, fontWeight: "700" }, options: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, option: { minWidth: 66, paddingVertical: 8, paddingHorizontal: 11, borderRadius: 9, backgroundColor: "#333333", alignItems: "center" }, optionActive: { backgroundColor: palette.navy }, optionText: { color: "#BDBDBD", fontSize: 11, fontWeight: "700" }, optionTextActive: { color: "#FFFFFF" }, colors: { flexDirection: "row", gap: 12 }, swatch: { width: 33, height: 33, borderRadius: 17, alignItems: "center", justifyContent: "center" }, swatchActive: { borderWidth: 2, borderColor: "#FFFFFF" }, row: { flexDirection: "row", alignItems: "center", minHeight: 38, gap: 10 }, rowText: { flex: 1, color: palette.text, fontSize: 13 }, saved: { flexDirection: "row", alignSelf: "flex-start", gap: 6, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8, backgroundColor: "#173B30" }, savedText: { color: "#6FE0B3", fontSize: 11, fontWeight: "700" } });
