import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { palette } from "@/components/hub-ui";
import { MidAutumnCampaignPanel } from "@/components/midautumn-campaign-panel";
import { ScreenContainer } from "@/components/screen-container";
import { useHub } from "@/lib/mcp-hub/context";
import { isMidAutumnCampaignActive } from "@/lib/midautumn-campaign";

type SettingRow = { icon: keyof typeof MaterialIcons.glyphMap; label: string; route?: "/chat" | "/providers" | "/models" | "/mcp" | "/chat-settings" | "/general-settings" | "/about" | "/copilots" | "/ai-cloud" | "/web-search" | "/document-parser" | "/archived-chats" | "/login" | "/admin" | "/bot-runner"; status?: boolean; action?: () => void };

export default function SettingsScreen() {
  const router = useRouter();
  const { state, clearAll } = useHub();
  const [accountUser, setAccountUser] = useState<{ role?: "user" | "admin" } | null>(null);
  const [midAutumnVisible, setMidAutumnVisible] = useState(false);
  useEffect(() => { void import("@/lib/_core/auth").then((Auth) => Auth.getUserInfo().then(setAccountUser)); }, []);
  const confirmClear = () => Alert.alert("Đặt lại dữ liệu", "Xoá toàn bộ provider, profile MCP, model đã lưu và API key trên thiết bị?", [{ text: "Huỷ", style: "cancel" }, { text: "Đặt lại", style: "destructive", onPress: () => void clearAll() }]);
  const rows: SettingRow[] = [{ icon: "cloud-done", label: "AI Cloud", route: "/ai-cloud", status: state.providers.some((item) => item.managedByApp && item.enabled) }, { icon: "account-circle", label: "Tài khoản / Đăng nhập", route: "/login", status: Boolean(accountUser) }, ...(accountUser?.role === "admin" ? [{ icon: "admin-panel-settings" as const, label: "Quản trị Cloud", route: "/admin" as const }] : []), { icon: "apps", label: "Model Provider", route: "/providers", status: state.providers.some((item) => !item.managedByApp && item.enabled) }, { icon: "view-in-ar", label: "Default Models", route: "/models" }, { icon: "travel-explore", label: "Web Search", route: "/web-search" }, { icon: "smart-toy", label: "Bot Runner", route: "/bot-runner" }, { icon: "image", label: "AI Tạo Ảnh", route: "/ai-image" }, { icon: "campaign", label: "Social Media Agent", route: "/social-agent" }, { icon: "description", label: "Document Parser", route: "/document-parser" }, { icon: "tune", label: "Chat Settings", route: "/chat-settings" }, { icon: "groups", label: "My Copilots", route: "/copilots" }, { icon: "inventory-2", label: "Archived Chats", route: "/archived-chats" }, { icon: "settings", label: "General Settings", route: "/general-settings" }, { icon: "hub", label: "MCP Servers", route: "/mcp", status: state.mcpServers.some((item) => item.enabled) }, { icon: "info-outline", label: "About", route: "/about" }];
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable testID="settings-back" onPress={() => router.replace("/chat")} style={styles.back}><MaterialIcons name="arrow-back-ios-new" size={18} color={palette.text} /></Pressable><Text style={styles.title}>Settings</Text><View style={styles.headerSpacer} pointerEvents="none" /></View><ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}>{isMidAutumnCampaignActive() ? <View style={styles.campaignWrap}><MidAutumnCampaignPanel compact onOpen={() => setMidAutumnVisible(true)} /></View> : null}{rows.map((row) => <Pressable key={row.label} onPress={() => row.route ? router.push(row.route as never) : row.action} style={({ pressed }) => [styles.row, { opacity: pressed ? 0.72 : 1 }]}><View style={styles.rowIcon}><MaterialIcons name={row.icon} size={22} color={row.label === "AI Cloud" ? palette.accent : palette.text} /></View><Text style={styles.rowLabel}>{row.label}</Text>{row.status ? <View style={styles.online} /> : null}<MaterialIcons name="chevron-right" size={24} color={palette.textMuted} /></Pressable>)}<Pressable onPress={confirmClear} style={({ pressed }) => [styles.reset, { opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="delete-outline" color={palette.error} size={18} /><Text style={styles.resetText}>Reset local data</Text></Pressable></ScrollView><MidAutumnCampaignPanel visible={midAutumnVisible} onClose={() => setMidAutumnVisible(false)} /></ScreenContainer>;
}

const styles = StyleSheet.create({ header: { height: 58, alignItems: "center", justifyContent: "center", borderBottomWidth: 1, borderColor: palette.border }, title: { color: palette.text, fontSize: 16, fontWeight: "800" }, back: { position: "absolute", left: 13, width: 40, height: 40, alignItems: "center", justifyContent: "center" }, headerSpacer: { position: "absolute", right: 13, width: 40, height: 40 }, list: { paddingBottom: 30 }, campaignWrap: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 4 }, row: { minHeight: 68, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderColor: palette.border }, rowIcon: { width: 28, alignItems: "center" }, rowLabel: { flex: 1, color: palette.text, fontSize: 14, fontWeight: "500" }, online: { width: 9, height: 9, borderRadius: 99, backgroundColor: palette.success, marginRight: 7 }, reset: { margin: 16, borderWidth: 1, borderColor: palette.border, borderRadius: 12, minHeight: 44, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, resetText: { color: palette.error, fontSize: 12, fontWeight: "800" } });
