import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useHub } from "@/lib/mcp-hub/context";

type SettingRow = { icon: keyof typeof MaterialIcons.glyphMap; label: string; route?: "/chat" | "/providers" | "/models" | "/mcp" | "/chat-settings" | "/general-settings" | "/about" | "/copilots" | "/ai-cloud" | "/web-search" | "/document-parser" | "/archived-chats"; status?: boolean; action?: () => void };

export default function SettingsScreen() {
  const router = useRouter();
  const { state, clearAll } = useHub();
  const confirmClear = () => Alert.alert("Đặt lại dữ liệu", "Xoá toàn bộ provider, profile MCP, model đã lưu và API key trên thiết bị?", [{ text: "Huỷ", style: "cancel" }, { text: "Đặt lại", style: "destructive", onPress: () => void clearAll() }]);
  const rows: SettingRow[] = [{ icon: "cloud-done", label: "AI Cloud", route: "/ai-cloud", status: state.providers.some((item) => item.managedByApp && item.enabled) }, { icon: "apps", label: "Model Provider", route: "/providers", status: state.providers.some((item) => !item.managedByApp && item.enabled) }, { icon: "view-in-ar", label: "Default Models", route: "/models" }, { icon: "travel-explore", label: "Web Search", route: "/web-search" }, { icon: "description", label: "Document Parser", route: "/document-parser" }, { icon: "tune", label: "Chat Settings", route: "/chat-settings" }, { icon: "groups", label: "My Copilots", route: "/copilots" }, { icon: "inventory-2", label: "Archived Chats", route: "/archived-chats" }, { icon: "settings", label: "General Settings", route: "/general-settings" }, { icon: "hub", label: "MCP Servers", route: "/mcp", status: state.mcpServers.some((item) => item.enabled) }, { icon: "info-outline", label: "About", route: "/about" }];
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable testID="settings-back" onPress={() => router.replace("/chat")} style={styles.back}><MaterialIcons name="arrow-back-ios-new" size={18} color={palette.text} /></Pressable><Text style={styles.title}>Settings</Text><View style={styles.headerSpacer} pointerEvents="none" /></View><ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}>{rows.map((row) => <Pressable key={row.label} onPress={() => row.route ? router.push(row.route as never) : row.action} style={({ pressed }) => [styles.row, { opacity: pressed ? 0.72 : 1 }]}><View style={styles.rowIcon}><MaterialIcons name={row.icon} size={22} color={row.label === "AI Cloud" ? "#FF7B39" : palette.text} /></View><Text style={styles.rowLabel}>{row.label}</Text>{row.status ? <View style={styles.online} /> : null}<MaterialIcons name="chevron-right" size={24} color="#999999" /></Pressable>)}<Pressable onPress={confirmClear} style={({ pressed }) => [styles.reset, { opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="delete-outline" color={palette.error} size={18} /><Text style={styles.resetText}>Reset local data</Text></Pressable></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ header: { height: 58, alignItems: "center", justifyContent: "center", borderBottomWidth: 1, borderColor: "#303030" }, title: { color: palette.text, fontSize: 16, fontWeight: "800" }, back: { position: "absolute", left: 13, width: 40, height: 40, alignItems: "center", justifyContent: "center" }, headerSpacer: { position: "absolute", right: 13, width: 40, height: 40 }, list: { paddingBottom: 30 }, row: { minHeight: 68, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderColor: "#303030" }, rowIcon: { width: 28, alignItems: "center" }, rowLabel: { flex: 1, color: "#E0E0E0", fontSize: 14, fontWeight: "500" }, online: { width: 9, height: 9, borderRadius: 99, backgroundColor: palette.success, marginRight: 7 }, reset: { margin: 16, borderWidth: 1, borderColor: "#7A3434", borderRadius: 12, minHeight: 44, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, resetText: { color: palette.error, fontSize: 12, fontWeight: "800" } });
