import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";

import { AppButton, Card, palette } from "@/components/hub-ui";
import { ScreenContainer } from "@/components/screen-container";
import { VideoScreenHeader } from "@/components/video-screen-header";
import { DEFAULT_WEB_SEARCH_SETTINGS, loadWebSearchSettings, saveWebSearchSettings, type WebSearchSettings } from "@/lib/mcp-hub/feature-settings";

export default function WebSearchScreen() {
  const [settings, setSettings] = useState<WebSearchSettings>(DEFAULT_WEB_SEARCH_SETTINGS); const [loaded, setLoaded] = useState(false);
  useEffect(() => { void loadWebSearchSettings().then((value) => { setSettings(value); setLoaded(true); }); }, []);
  const save = async (next: WebSearchSettings) => { setSettings(next); await saveWebSearchSettings(next); };
  const option = (label: string, value: string, active: boolean, onPress: () => void) => <Pressable key={value} onPress={onPress} style={[styles.option, active && styles.optionActive]}><Text style={[styles.optionText, active && styles.optionTextActive]}>{label}</Text></Pressable>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><VideoScreenHeader title="Web Search" /><View style={styles.content}><Card style={styles.hero}><MaterialIcons name="travel-explore" size={25} color={palette.navy} /><View style={{ flex: 1 }}><Text style={styles.heroTitle}>Tìm kiếm web trong Chat</Text><Text style={styles.detail}>Khi bật, model có hỗ trợ sẽ nhận plugin web search trong tin nhắn mới.</Text></View><Switch value={settings.enabledByDefault} onValueChange={(value) => void save({ ...settings, enabledByDefault: value })} trackColor={{ false: "#4A4A4A", true: palette.navy }} thumbColor="#FFFFFF" /></Card><Text style={styles.section}>Phạm vi mặc định</Text><Card style={styles.card}><View style={styles.options}>{option("Web", "web", settings.scope === "web", () => void save({ ...settings, scope: "web" }))}{option("News", "news", settings.scope === "news", () => void save({ ...settings, scope: "news" }))}</View></Card><Text style={styles.section}>Ngôn ngữ tìm kiếm</Text><Card style={styles.card}><View style={styles.options}>{option("Tiếng Việt", "vi", settings.language === "vi", () => void save({ ...settings, language: "vi" }))}{option("Tự động", "auto", settings.language === "auto", () => void save({ ...settings, language: "auto" }))}</View></Card><Card style={styles.note}><MaterialIcons name="info-outline" color="#6DBBFF" size={18} /><Text style={styles.noteText}>Bạn vẫn có thể bật/tắt Web Search cho từng tin nhắn bằng biểu tượng kính lúp ở composer. Cài đặt này áp dụng làm mặc định khi mở Chat.</Text></Card><AppButton label={loaded ? "Đã lưu cài đặt" : "Đang tải"} icon="check" disabled={!loaded} onPress={() => void save(settings)} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { flex: 1, padding: 14, gap: 10 }, hero: { flexDirection: "row", alignItems: "center", gap: 10 }, heroTitle: { color: palette.text, fontSize: 14, fontWeight: "800", marginBottom: 3 }, detail: { color: palette.muted, fontSize: 11, lineHeight: 16 }, section: { color: palette.text, fontSize: 13, fontWeight: "800", marginTop: 5 }, card: { padding: 10 }, options: { flexDirection: "row", gap: 8 }, option: { paddingHorizontal: 12, paddingVertical: 8, minWidth: 76, alignItems: "center", borderRadius: 9, backgroundColor: "#363636" }, optionActive: { backgroundColor: palette.navy }, optionText: { color: "#C5C5C5", fontSize: 11, fontWeight: "700" }, optionTextActive: { color: "#FFFFFF" }, note: { flexDirection: "row", gap: 8, backgroundColor: "#213C53", borderColor: "#416179" }, noteText: { flex: 1, color: "#BFE1FF", fontSize: 11, lineHeight: 16 } });
